//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCDNewMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictBlock_Master
    {
        public int Id { get; set; }
        public string volunteer_name { get; set; }
        public string volunteer_mobile { get; set; }
        public string block_name { get; set; }
        public string block_id { get; set; }
        public string chc_name { get; set; }
        public string chc_id { get; set; }
        public string phc_name { get; set; }
        public string phc_id { get; set; }
        public string sc_name { get; set; }
        public string sc_id { get; set; }
        public string panchayat_name { get; set; }
        public string panchayat_id { get; set; }
        public string village_name { get; set; }
        public string village_id { get; set; }
        public string screening_type { get; set; }
        public string household_id { get; set; }
        public string household_name { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime createdAt { get; set; }
        public string CreatedBy { get; set; }
    }
}
