//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCDNewMIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NCD_DBEntities : DbContext
    {
        public NCD_DBEntities()
            : base("name=NCD_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Register> tbl_Register { get; set; }
        public virtual DbSet<tbl_Login> tbl_Login { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Block_Master> Block_Master { get; set; }
        public virtual DbSet<CHC_Master> CHC_Master { get; set; }
        public virtual DbSet<District_Master> District_Master { get; set; }
        public virtual DbSet<DistrictBlock_Master> DistrictBlock_Master { get; set; }
        public virtual DbSet<GP_Master> GP_Master { get; set; }
        public virtual DbSet<PHC_Master> PHC_Master { get; set; }
        public virtual DbSet<TBL_Emp> TBL_Emp { get; set; }
        public virtual DbSet<tbl_RegMappping> tbl_RegMappping { get; set; }
    }
}
