//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCDNewMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register
    {
        public int RegId_pk { get; set; }
        public string FullName { get; set; }
        public string Password { get; set; }
        public string MobileNo { get; set; }
        public string Version { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
